### ISSUE TITLE
ImportError: libcudart.so.8.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by a785448726** [HKUST-Aerial-Robotics/Stereo-RCNN#5]
How to solve this “ImportError: libcudart.so.8.0: cannot open shared object file: No such file or directory“？

**Comment by PeiliangLi** [comment]
Which version of the CUDA have you installed?
You need to specify the corresponding cuda version when installing pytorch: conda install pytorch=0.3.0 **your_CUDA_version**(cuda80/cuda90, etc) -c pytorch

**Comment by a785448726** [comment]
The version I installed was cuda80

**Comment by PeiliangLi** [comment]
What's your `nvcc --version` outputs and 
```
python
import torch
torch.__version__
```

**Comment by PeiliangLi** [comment]
run 
`conda install cudatoolkit=8.0`
will solve this issue

**Comment by a785448726** [comment]
Thank you very much，the previous problem was solved. But now there is a new problem: "ImportError: No module named cython_bbox". I see you've answered this question before, and I make an error when I run make.sh.

**Comment by PeiliangLi** [comment]
Hi, I found the issue just now.
The simplest way is removing this line:
`model.utils.cython_bbox import bbox_overlaps` in the imdb.py
